# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: "5 4 * * *"
jobs:
  cleaning:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clean
        uses: beatlabs/delete-old-branches-action@v0.0.6
        with:
          repo_token: ${{ GH_Secert.GH_TOKEN }}
          date: '2 month ago'
          dry_run: true
          delete_tags: true
          minimum_tags: 5
          extra_protected_branch_regex: master.*|main|develop|^release.*|.*_p$
