# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Stale Branches

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Stale Branches
      uses: crs-k/stale-branches@v3.0.0
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
        days-before-stale: 0
        days-before-delete: 1
        comment-updates: false
        max-issues: 20
        tag-committer: false
        branches-filter-regex: '^((?!master))'
